name: Automatically update Flatcar docs on Branch Push
on:
  push:
    branches:
      - master

jobs:
  auto-flatcar-docs:
    name: Automatically update Flatcar docs
    runs-on: ubuntu-latest
    steps:
      - name: ssh-agent
        uses: webfactory/ssh-agent@v0.2.0
        with:
          #ssh-private-key: ${{ secrets.FLATCAR_DOCS_KEY }}
          ssh-private-key: ${{ secrets.FLATCAR_WEBSITE_DOCS_GITHUB_ACTIONS_KEY }}
      - name: set up git user
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #ssh-private-key: ${{ secrets.FLATCAR_DOCS_KEY }}
          ssh-private-key: ${{ secrets.FLATCAR_WEBSITE_DOCS_GITHUB_ACTIONS_KEY }}
        run: |
          git config --global user.name 'Flatcar Buildbot'
          git config --global user.email 'buildbot@flatcar-linux.org'
          #git clone git@github.com:dongsupark/docs-test docs.flatcar-linux.org
          #git clone https://github.com/kinvolk/flatcar-website-docs
          git clone git@github.com:kinvolk/flatcar-website-docs.git
          pushd flatcar-website-docs || exit
          make fetch-docs
          python3 -m venv .
          source bin/activate
          make build
          make copy-build
          popd || exit
          pushd docs.flatcar-linux.org
          git commit -a -m "Update Flatcar docs ($(date +'%Y-%m-%d'))"
          git checkout -B site.test site
          git push origin site.test
          popd || exit
